\set ON_ERROR_STOP on
DROP SCHEMA IF EXISTS public;
CREATE SCHEMA IF NOT EXISTS :source_schema;
GRANT USAGE ON SCHEMA :source_schema TO PUBLIC;
GRANT ALL ON SCHEMA :source_schema TO GROUP ohdsi_admin;
GRANT USAGE ON SCHEMA :source_schema TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :source_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :source_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_admin;

CREATE SCHEMA IF NOT EXISTS :working_schema;
GRANT USAGE ON SCHEMA :working_schema TO PUBLIC;
GRANT ALL ON SCHEMA :working_schema TO GROUP ohdsi_admin;
GRANT USAGE ON SCHEMA :working_schema TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :working_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :working_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_admin;

CREATE SCHEMA IF NOT EXISTS :production_schema;
GRANT USAGE ON SCHEMA :production_schema TO PUBLIC;
GRANT ALL ON SCHEMA :production_schema TO GROUP ohdsi_admin;
GRANT USAGE ON SCHEMA :production_schema TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :production_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :production_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_admin;

CREATE SCHEMA IF NOT EXISTS :atlasresult_schema;
GRANT USAGE ON SCHEMA :atlasresult_schema TO PUBLIC;
GRANT ALL ON SCHEMA :atlasresult_schema TO GROUP ohdsi_admin;
GRANT USAGE ON SCHEMA :atlasresult_schema TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :atlasresult_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :atlasresult_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_admin;

CREATE SCHEMA IF NOT EXISTS :temp_schema;
GRANT USAGE ON SCHEMA :temp_schema TO PUBLIC;
GRANT ALL ON SCHEMA :temp_schema TO GROUP ohdsi_admin;
GRANT USAGE ON SCHEMA :temp_schema TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :temp_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA :temp_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO GROUP ohdsi_admin;
